#!/bin/bash

set -euo pipefail
shopt -s nullglob globstar

if [[ $# -eq 0 ]] ; then
    echo 'No snapper config supplied'
    exit 0
fi

readonly SNAPPER_CONFIG=$1

if [ ! -f /etc/snapper/configs/$SNAPPER_CONFIG ]; then
    echo 'No snapper config with this name'
    exit 0
fi

NETWORK_TIMEOUT=120
i=0
while [ "$(nmcli -g connectivity general status)" = "none" ]; do
    i=$[$i+1]
    if [ $i -gt "$NETWORK_TIMEOUT" ]; then
        echo "Network not up, skipping upload" >&2
        exit 0
    fi
    sleep 1
done


source /etc/snapper/configs/$SNAPPER_CONFIG

export BORG_PASSPHRASE="$(pass backup/$(hostname))"
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export BORG_RSH="ssh -i /home/fox/.ssh/machine"

LATEST_SNAPSHOT="$(snapper -c $SNAPPER_CONFIG list | grep timeline | tail -n1 | awk -F\| '{print $2}' | tr -d ' ')"

if ! BORG_LIST="$(borg list borg@velox.vulpes.pw:$(hostname)/$SNAPPER_CONFIG | tail -n 1 | awk '{print $3}')"; then
    borg init --umask 0027 --encryption=repokey-blake2 borg@velox.vulpes.pw:$(hostname)/$SNAPPER_CONFIG
fi


if [[ $(date "+%Y%m%d") -gt ${BORG_LIST//-} ]];
then
    notify-send "Started $SNAPPER_CONFIG backup"
    sudo backup-sudo mount "${SUBVOLUME%/}/.snapshots/$LATEST_SNAPSHOT" "${SUBVOLUME%/}/.snapshots/backup"
    cleanup() {
        sudo backup-sudo cleanup "${SUBVOLUME%/}/.snapshots/backup"
    }
    trap cleanup EXIT
    if ! borg create --umask 0027 -v -p --stats -C lz4 \
        -e "*/proc" \
        -e "*/sys" \
        -e "*/dev" \
        -e "*/run" \
        -e "*/tmp" \
        -e "*/var/cache" \
        -e "*/.cache" \
        -e "*/Media" \
        -e "*/Bilder" \
        -e "*/Pictures" \
        -e "*/Downloads" \
        -e "*/var/lib/archbuild" \
        -e "*/var/lib/build" \
        -e "*/.config/borg/security" \
        -e "*/.snapshots/backup/snapshot/.snapshots" \
        -e "*/.snapshots/backup/info.xml" \
    borg@velox.vulpes.pw:$(hostname)/$SNAPPER_CONFIG::$(date "+%Y%m%d-%H%M%S") "${SUBVOLUME%/}/.snapshots/backup"; then
        notify-send -u critical "Backup $SNAPPER_CONFIG failed!"
    fi
    notify-send "$SNAPPER_CONFIG backup done"
    borg prune --umask 0027 -v borg@velox.vulpes.pw:$(hostname)/$SNAPPER_CONFIG \
        --keep-daily="$TIMELINE_LIMIT_DAILY" \
        --keep-weekly="$TIMELINE_LIMIT_WEEKLY" \
        --keep-monthly="$TIMELINE_LIMIT_YEARLY"
else
    echo "Allready have a backup with the given date"
fi
