#!/bin/bash

export XAUTHORITY=/run/user/1000/Xauthority
export DISPLAY=:0

connect(){
    echo "Connecting..."
    sleep 1
	xrandr --output DP1-2 --left-of eDP1 --mode 1920x1200
	xrandr --output DP1-1 --right-of eDP1 --mode 1920x1200
	xrandr --output DP1-1 --left-of DP1-2 --mode 1920x1200
}

disconnect(){
    echo "Disconnecting..."
	xrandr --auto
}

case "$1" in 
	connect)
		connect
		;;
	disconnect)
		disconnect
		;;
    *)
        echo $"Usage: $0 {connect|disconnect}"
        exit 1
esac
